name: aohw25_390
channels:
  - conda-forge
dependencies:
  - python=3.11.13
  - numpy=1.26.4
  - scikit-learn=1.7.1
  - tensorflow=2.15.0
  - tf-keras=2.15.0
  - cuda-version=12.2
  - cudnn=8.9.7.29
  - matplotlib=3.10.5
  - pip=25.2
  - pip:
      - qkeras==0.9.0
      - hls4ml==1.1.0
